/**
 * 渲染器：`.sdo/` 真源 → 人类文档（设计 §10.1 / §10.2）。
 *
 * 纪律：
 *   · 文件头必须声明「生成物、勿手改」与真源位置 + journal `seq`（设计 §10.1 原文格式）；
 *   · **幂等**：同一状态 + 同一 `seq` 必须渲染出逐字节相同的文本（便于反复调用与 diff）；
 *   · 排序确定（需求按 ID、问题按 ID），不依赖文件系统顺序。
 */
import { readFileSync } from 'node:fs'
import { dirname, join } from 'node:path'
import { fileURLToPath } from 'node:url'

import { formatId } from './ids.js'
import { textOf } from './scalar.js'
import { isEffectivelyOpen } from '../domain/dor.js'
import { DIMENSIONS } from '../types.js'
import type { GrillQuestion, Requirement, SdoProject } from '../types.js'

/** 渲染头：生成者与真源（设计 §10.1 的原文格式）。 */
export function renderHeader(source: string, seq: number): string {
  return [
    `<!-- generated by dsh-software-dev-office v${packageVersion()} from .sdo/ ; DO NOT EDIT -->`,
    `<!-- source: ${source} @ journal seq ${seq} -->`,
  ].join('\n')
}

/**
 * 渲染**元信息**头行（N-8 / N-11）：语言与阶段等"说明性"字段。
 *
 * 为什么不放进正文：`docs/DESIGN.md` 的判据要能把**正文**与"当前真源的重渲染结果"逐字节比对
 * （这才叫"文档即证据"）；凡是**不源于设计真源**的字段（当前语言、当前阶段）放进正文就会让
 * 每次 `advance` / 切语言都把文档判成"与真源不一致"。它们放在注释头里，仅作说明。
 */
export function renderMeta(lang: string, phase: string): string {
  return `<!-- meta: lang ${lang} ; phase ${phase} -->`
}

/** 归一化末尾换行（`SdoStore.writeText` 会给没有尾换行的文本补一个）。 */
export function stripTrailingNewlines(text: string): string {
  return text.replace(/\n+$/u, '')
}

let cachedVersion: string | undefined

/** 读取本包版本（用于渲染头）。 */
export function packageVersion(): string {
  if (cachedVersion !== undefined) return cachedVersion
  let dir = dirname(fileURLToPath(import.meta.url))
  for (let i = 0; i < 8; i++) {
    try {
      const raw = JSON.parse(readFileSync(join(dir, 'package.json'), 'utf8')) as { version?: string }
      if (typeof raw.version === 'string' && raw.version !== '') {
        cachedVersion = raw.version
        return cachedVersion
      }
    } catch {
      /* 继续向上找 */
    }
    const parent = dirname(dir)
    if (parent === dir) break
    dir = parent
  }
  cachedVersion = '0.0.0'
  return cachedVersion
}

/** SRS 渲染输入。 */
export interface SrsInput {
  project: SdoProject | undefined
  requirements: Requirement[]
  questions: GrillQuestion[]
  /** 当前 journal 序号（写进渲染头） */
  seq: number
}

function bulletList(items: string[]): string {
  return items.length === 0 ? '_（无）_\n' : `${items.map((item) => `- ${item}`).join('\n')}\n`
}

/** 渲染 SRS（软件需求规格说明）。 */
export function renderSrs(input: SrsInput): string {
  const lines: string[] = []
  lines.push(renderHeader('.sdo/requirements/*.yml', input.seq))
  lines.push('')
  lines.push('# 软件需求规格说明（SRS）')
  lines.push('')

  const project = input.project
  if (project === undefined) {
    lines.push('> 尚未初始化项目（没有 `.sdo/project.json`）。')
    return `${lines.join('\n')}\n`
  }

  lines.push(`- 项目：**${project.id} ${project.name}**`)
  lines.push(`- 流程：${project.process} ｜ 阶段：${project.phase} ｜ 规模：${project.tailoring?.scale ?? 'normal'}`)
  lines.push(`- 需求条目：${input.requirements.length} 条 ｜ 未决问题：${input.questions.filter((q) => isEffectivelyOpen(q)).length} 条`)
  lines.push('')

  lines.push('## 1. 范围')
  lines.push('')
  lines.push('### 1.1 目标（in）')
  lines.push('')
  lines.push(bulletList(project.scope.in))
  lines.push('### 1.2 非目标（out）')
  lines.push('')
  lines.push(bulletList(project.scope.out))

  lines.push('## 2. 干系人')
  lines.push('')
  lines.push(
    project.stakeholders.length === 0
      ? '_（无）_\n'
      : `${project.stakeholders.map((stakeholder) => `- ${stakeholder.id}　${stakeholder.role}${stakeholder.concerns.length > 0 ? `　关注：${stakeholder.concerns.join('、')}` : ''}`).join('\n')}\n`,
  )

  lines.push('## 3. 术语表')
  lines.push('')
  const terms = Object.entries(project.glossary)
  lines.push(terms.length === 0 ? '_（无）_\n' : `${terms.map(([term, definition]) => `- **${term}**：${definition}`).join('\n')}\n`)

  lines.push('## 4. 成功度量')
  lines.push('')
  lines.push('### 4.1 成功指标')
  lines.push('')
  lines.push(bulletList(project.metrics.success))
  lines.push('### 4.2 护栏指标')
  lines.push('')
  lines.push(bulletList(project.metrics.guardrail))

  lines.push('## 5. 需求')
  lines.push('')
  if (input.requirements.length === 0) {
    lines.push('_（还没有需求；用 `sdo_requirement action=capture` 收集）_')
    lines.push('')
  }
  const sorted = [...input.requirements].sort((a, b) => a.id.localeCompare(b.id))
  for (const requirement of sorted) {
    lines.push(`### 5.${sorted.indexOf(requirement) + 1} ${requirement.id}　${requirement.title}`)
    lines.push('')
    lines.push(`- 类型：${requirement.kind} ｜ 优先级：${requirement.priority ?? '（未定）'} ｜ 状态：${requirement.status} ｜ 版本：${requirement.version}`)
    lines.push(`- 歧义评分：${requirement.ambiguity.score}/16（${DIMENSIONS.map((dimension) => `${dimension} ${requirement.ambiguity.dimensions[dimension] ?? 0}`).join(' ｜ ')}）`)
    if (requirement.ambiguity.open.length > 0) {
      lines.push(`- 未决问题：${requirement.ambiguity.open.join(' ')}`)
    }
    const source = requirement.source.stakeholder ?? requirement.source.raw ?? '（未记录来源）'
    lines.push(`- 来源：${source}`)
    lines.push('')
    lines.push(`**陈述**：${requirement.statement}`)
    lines.push('')
    if (textOf(requirement.rationale).trim() !== '') {
      lines.push(`**理由**：${requirement.rationale}`)
      lines.push('')
    }
    if (requirement.acceptance.length === 0) {
      lines.push('**验收标准**：（无）')
      lines.push('')
    } else {
      lines.push('**验收标准**：')
      lines.push('')
      for (const ac of requirement.acceptance) {
        lines.push(`- ${ac.id}　Given：${ac.given}；When：${ac.when}；Then：${ac.then}`)
      }
      lines.push('')
    }
  }

  lines.push('## 6. 开环问题')
  lines.push('')
  // **P-6**：与门禁同源（未授权假设仍算未决）—— 否则门禁说"有 1 条未决"而文档写"（无）"
  const open = input.questions.filter((question) => isEffectivelyOpen(question)).sort((a, b) => a.id.localeCompare(b.id))
  if (open.length === 0) {
    lines.push('_（无）_')
    lines.push('')
  } else {
    for (const question of open) {
      lines.push(`- **${question.id}**（${question.severity}／${question.dimension}）${question.text}`)
      lines.push(`  - 目标：${question.targets.join(' ')}　原因：${question.why}`)
      lines.push(`  - 不问的后果：${question.consequenceIfUnasked}`)
      for (const option of question.options) {
        lines.push(`  - 选项：${option.label}（代价：${option.cost}）`)
      }
      lines.push(`  - 默认建议：${question.defaultRecommendation}`)
    }
    lines.push('')
  }

  return `${lines.join('\n')}\n`
}

/** 便捷：把需求 ID 序号格式化（供渲染与工具输出）。 */
export function requirementLabel(index: number): string {
  return formatId('REQ', index)
}
